import type { BusinessProfile, GovernmentScheme, LocalMarketData, Entrepreneur } from './types'

export const demoEntrepreneur: Entrepreneur = {
  name: 'Ravi Kumar', age: 31, gender: 'Male', location: { state: 'Uttar Pradesh', district: 'Sitapur', block: 'Maholi', village: 'Demo Village', marketDistance: 6 },
  annualIncome: 240000, ownCapital: 30000, language: 'en', skills: ['Animal care', 'Basic sales'], experience: 'some', land: 'available', electricity: 'available', water: 'available', connectivity: 'available', transport: 'limited', assets: 'Small cattle shed; smartphone', interest: 'dairy', category: 'Scheduled Caste (demo)'
}

export const demoMarket: LocalMarketData = {
  village: 'Demo Village', population: 4500, households: 850, marketDistance: 6,
  existingBusinesses: { Grocery: 5, Dairy: 2, 'Mobile repair': 0, Tailoring: 2, Poultry: 1, 'Vegetable farming': 12 },
  demand: { dairy: 'high', poultry: 'medium', goat: 'high', mushroom: 'medium', grocery: 'medium', mobile: 'high', tailoring: 'medium', food: 'medium', vegetable: 'high', retail: 'medium' },
  notes: 'Demo/local-market estimate — replace with verified local data in production.'
}

export const businesses: BusinessProfile[] = [
  { id:'dairy', name:'Dairy Farming', nameHi:'डेयरी पालन', category:'Livestock', startupCost:120000, minCapital:15000, equipmentCost:35000, monthlyExpenses:14500, revenueLow:26000, revenueHigh:38000, profitLow:8000, profitHigh:18000, risk:'Medium', skills:['Animal care','Basic sales'], land:true,electricity:true,water:true,marketDependency:'High',seasonality:'Low',customers:['Households','Tea shops','Local dairy collection'],description:'Small-scale milk production with local collection or direct household sales.',descriptionHi:'स्थानीय संग्रह केंद्र या घरों में सीधे बिक्री के लिए छोटे पैमाने पर दूध उत्पादन।' },
  { id:'poultry', name:'Poultry Farming', nameHi:'कुक्कुट पालन', category:'Livestock', startupCost:95000, minCapital:12000, equipmentCost:28000, monthlyExpenses:18000, revenueLow:30000, revenueHigh:43000, profitLow:7000, profitHigh:16000, risk:'High',skills:['Animal care'],land:true,electricity:true,water:true,marketDependency:'High',seasonality:'Medium',customers:['Households','Meat shops','Restaurants'],description:'Broiler or layer unit sized for a village market.',descriptionHi:'गाँव के बाजार के अनुकूल ब्रॉयलर या लेयर यूनिट।' },
  { id:'goat', name:'Goat Farming', nameHi:'बकरी पालन', category:'Livestock', startupCost:110000,minCapital:15000,equipmentCost:18000,monthlyExpenses:8500,revenueLow:18000,revenueHigh:30000,profitLow:6500,profitHigh:14500,risk:'Medium',skills:['Animal care'],land:true,electricity:false,water:true,marketDependency:'Medium',seasonality:'Medium',customers:['Local households','Traders'],description:'Small goat-rearing unit with staged breeding and sale.',descriptionHi:'चरणबद्ध प्रजनन और बिक्री वाली छोटी बकरी पालन इकाई।' },
  { id:'mushroom',name:'Mushroom Farming',nameHi:'मशरूम उत्पादन',category:'Agriculture',startupCost:80000,minCapital:10000,equipmentCost:30000,monthlyExpenses:9000,revenueLow:21000,revenueHigh:34000,profitLow:7000,profitHigh:17000,risk:'Medium',skills:['Food handling','Basic farming'],land:false,electricity:true,water:true,marketDependency:'High',seasonality:'Medium',customers:['Retailers','Hotels','Households'],description:'Indoor oyster mushroom production with a controlled growing space.',descriptionHi:'नियंत्रित स्थान में ऑयस्टर मशरूम का उत्पादन।' },
  { id:'grocery',name:'Grocery Store',nameHi:'किराना दुकान',category:'Retail',startupCost:140000,minCapital:25000,equipmentCost:20000,monthlyExpenses:9000,revenueLow:35000,revenueHigh:60000,profitLow:6500,profitHigh:14000,risk:'Medium',skills:['Sales','Inventory'],land:false,electricity:true,water:false,marketDependency:'High',seasonality:'Low',customers:['Village households'],description:'Essential-goods retail outlet for nearby households.',descriptionHi:'आसपास के परिवारों के लिए आवश्यक वस्तुओं की खुदरा दुकान।' },
  { id:'mobile',name:'Mobile Repair & Accessories',nameHi:'मोबाइल मरम्मत और एक्सेसरीज़',category:'Service',startupCost:70000,minCapital:10000,equipmentCost:38000,monthlyExpenses:5000,revenueLow:18000,revenueHigh:36000,profitLow:8000,profitHigh:20000,risk:'Low',skills:['Mobile repair','Customer service'],land:false,electricity:true,water:false,marketDependency:'Medium',seasonality:'Low',customers:['Students','Households','Farmers'],description:'Repair desk and accessories counter for an underserved local market.',descriptionHi:'कम सेवा वाले स्थानीय बाजार के लिए मरम्मत डेस्क और एक्सेसरी काउंटर।' },
  { id:'tailoring',name:'Tailoring',nameHi:'सिलाई केंद्र',category:'Service',startupCost:60000,minCapital:8000,equipmentCost:35000,monthlyExpenses:4000,revenueLow:14000,revenueHigh:28000,profitLow:6000,profitHigh:15000,risk:'Low',skills:['Tailoring'],land:false,electricity:true,water:false,marketDependency:'Medium',seasonality:'High',customers:['Women','Students','Local shops'],description:'Home or shop-based stitching, alterations and school uniform work.',descriptionHi:'घर या दुकान से सिलाई, अल्टरशन और स्कूल यूनिफॉर्म का काम।' },
  { id:'food',name:'Food Processing',nameHi:'खाद्य प्रसंस्करण',category:'Manufacturing',startupCost:180000,minCapital:30000,equipmentCost:75000,monthlyExpenses:22000,revenueLow:42000,revenueHigh:70000,profitLow:9000,profitHigh:23000,risk:'Medium',skills:['Food handling','Sales'],land:false,electricity:true,water:true,marketDependency:'High',seasonality:'Medium',customers:['Retailers','Households','Markets'],description:'Small-scale processing of local grains, spices or snacks.',descriptionHi:'स्थानीय अनाज, मसाले या स्नैक्स का छोटे स्तर पर प्रसंस्करण।' },
  { id:'vegetable',name:'Vegetable Farming',nameHi:'सब्ज़ी खेती',category:'Agriculture',startupCost:90000,minCapital:12000,equipmentCost:20000,monthlyExpenses:11000,revenueLow:24000,revenueHigh:42000,profitLow:6500,profitHigh:18000,risk:'High',skills:['Farming'],land:true,electricity:false,water:true,marketDependency:'High',seasonality:'High',customers:['Market vendors','Households'],description:'Seasonal vegetable cultivation linked to nearby markets.',descriptionHi:'नजदीकी बाजारों से जुड़ी मौसमी सब्ज़ी की खेती।' },
  { id:'retail',name:'Small Retail',nameHi:'छोटा खुदरा व्यवसाय',category:'Retail',startupCost:100000,minCapital:15000,equipmentCost:15000,monthlyExpenses:6000,revenueLow:28000,revenueHigh:48000,profitLow:6000,profitHigh:16000,risk:'Medium',skills:['Sales','Inventory'],land:false,electricity:true,water:false,marketDependency:'High',seasonality:'Low',customers:['Village households'],description:'Focused retail counter for household and farm essentials.',descriptionHi:'घरेलू और कृषि जरूरतों के लिए केंद्रित खुदरा काउंटर।' }
]

export const schemes: GovernmentScheme[] = [
 { id:'micro',name:'Micro Finance Scheme',projectMin:0,projectMax:140000,maxLoan:125000,interest:'6.5% p.a.',numericInterest:6.5,tenure:'3 years incl. 3-month moratorium',tenureYears:3,moratoriumMonths:3,frequency:'quarterly',source:'myScheme official information',eligibility:['Eligible Scheduled Caste beneficiary','Annual family income up to ₹5 lakh','Valid caste certificate; channel-specific requirements'] },
 { id:'term',name:'Term Loan',projectMin:140001,projectMax:5000000,maxLoan:4500000,interest:'8% p.a.',numericInterest:8,tenure:'Up to 7 years incl. 6-month moratorium',tenureYears:7,moratoriumMonths:6,frequency:'not_stated',source:'myScheme official information',eligibility:['Eligible Scheduled Caste beneficiary','Annual family income up to ₹5 lakh','Authorized channelizing agency route'] },
 { id:'udyam',name:'Udyam Nidhi Yojana',projectMin:0,projectMax:500000,maxLoan:450000,interest:'13% (Co-op/Banks) / 15% (SFB)',numericInterest:13,tenure:'5 years incl. 3-month moratorium',tenureYears:5,moratoriumMonths:3,frequency:'not_stated',channel:'Rate varies by channel',source:'myScheme official information',eligibility:['Eligible Scheduled Caste beneficiary','Annual family income up to ₹5 lakh','Channel-specific terms and documents'] }
]
